[build]
  publish = "public"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "https://hellocode.dev"
  to =  "https://blog.matt-thorning.dev"
  status = 301
  force = true
